### ISSUE TITLE
Weird behavior on autoformat 

### ISSUE THREAD

**Issue by otbe** [MaxGabriel/brittany-vscode-extension#1]
Hi,

I started using your extension to use brittany as my formatter within vscode. It works somehow but I get a weird behavior for multiple save actions in a row.

Lets say this is my content:
<img width="343" alt="bildschirmfoto 2018-03-17 um 10 02 25" src="https://user-images.githubusercontent.com/3391052/37553546-92521c8a-29ca-11e8-9b2f-6b577735940f.png">

I change it to:
<img width="314" alt="bildschirmfoto 2018-03-17 um 10 02 53" src="https://user-images.githubusercontent.com/3391052/37553549-a5fc5b24-29ca-11e8-9fee-5acf8fd3e5e6.png">

After I hit save vscode will format my code with brittany as I expect, but the content flips back to the first screen. So "Anonymous5" becomes "Anonymous4" again. It seems that this extension replaces all of my modifications with the original version of the file.

Any idea whats wrong with my setup? Notice it works with brittany from the command line.

I use the latest vscode insiders.

Thanks

**Comment by MaxGabriel** [comment]
Can you clarify what you mean by “multiple save actions in a row”? How long is the time between saving?

The plugin runs Brittany asynchronously, so if it’s rapid saves I’m wondering if an old run of Brittany is replacing the new content. This could maybe be solved by checking if the file has changed since Brittany was started before writing new content, I think.

If there’s more than a few seconds between saves, it sounds like it’s something else.

Does that theory sound correct to you? This was my first typescript program, and the code is pretty simple if you want to take a look at what it’s doing.

**Comment by otbe** [comment]
Thanks for you fast reponse :)

Actually "multiple save actions in a row" means at least two save actions within the same file. It makes no difference if I wait 1s or 1m.

> This could maybe be solved by checking if the file has changed since Brittany was started before writing new content, I think.

That sounds reasonable. 

I will have a look later this day.
Btw great work!

**Comment by MaxGabriel** [comment]
Thanks. Btw, I’m stuck in traffic on the way to Bishop California right now, so I won’t be able to take a closer look for at least a few days.

**Comment by otbe** [comment]
Ive done a quick debug session. It seems that brittany reads the old content from the filesystem instead of the recently changed one. Maybe your extensions runs before the file is synced to the filesystem?

A quickfix is to check if the `TextDocument` is dirty and if it is call `save()`. This works on my local machine 😕

**Comment by skeet70** [comment]
Noticed this same issue immediately. Trying to save with non-existent variables shows errors in the 'problems' tab and doesn't finish formatting. If I fix those variables and re-save, it correctly formats but also changes the variables back to the old incorrect ones.

**Comment by obcode** [comment]
same problem here

**Comment by mnxn** [comment]
Closed by #4
