### ISSUE TITLE
Stopped working after additionalFlags fix (Windows 10)

### ISSUE THREAD

**Issue by ivxvm** [MaxGabriel/brittany-vscode-extension#17]
After the last update, extension doesn't work when "brittany.additionalFlags" are empty.
Example error:
```
Failed to run brittany; see the developer tools console for details. 
Error: Command failed: brittany --write-mode display : openBinaryFile: does not exist (No such file or directory)
```
As a workaround, adding this to settings fixes the issue for me:
```json
"brittany.additionalFlags": "--indent 4",
```
I've played a little bit with the relevant JS in browser console, and my guess the problem is this:
https://github.com/MaxGabriel/brittany-vscode-extension/blob/master/src/formatter.ts#L118
Pushes an empty string to args which for some reason ruins the process.
I'm not familiar with VS Code extensions development, so can't test it to make a quick PR.

**Comment by mnxn** [comment]
Thanks for the issue. I'll take a look at this in a bit

**Comment by mnxn** [comment]
Just released a pretty simple fix. Sorry for not catching it earlier.
