### ISSUE TITLE
Add support for stack

### ISSUE THREAD

**Issue by eborden** [MaxGabriel/brittany-vscode-extension#2]
It is common to run binaries like `brittany` from `stack` using `stack exec brittany`. This helps projects utilize a pinned version of the tool via `stack build brittany --copy-compiler-tool`. I'd love to see this plugin support `stack` workflows like this, with less configuration.

The current work around is to copy the compiler tools bin path into the config, but this is fragile and will break on snapshot updates.

**Comment by mnxn** [comment]
Closed with #5

**Comment by eborden** [comment]
Thanks @mnxn!
