### ISSUE TITLE
Stack's version warning is considered as error

### ISSUE THREAD

**Issue by openingnow** [MaxGabriel/brittany-vscode-extension#22]
When using stack with GHC8.8, stack emits follwing warnings via stderr.
```
Stack has not been tested with GHC versions above 8.6, and using 8.8.2, this may fail
Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail
```
Despite of these messages, brittany works fine with GHC 8.8.

Below is an typical error message with incorrect syntax.
```
Command failed: brittany --write-mode display
parse error:
"RealSrcSpan SrcSpanOneLine \"stdin\" 9 26 28: parse error on input \8216le\8217"
```
https://github.com/MaxGabriel/brittany-vscode-extension/blob/e4c1820b73fee4a89646434276a82e8e0cd34c05/src/formatter.ts#L154-L158

IMHO checking if `err` contains `parse error` or ignoring line starts with `Stack has not been tested with` could be a workaround.

**Comment by mnxn** [comment]
If you run `stack --silent exec brittany` from the command line, does it still show the version errors?

I'd rather not use any string manipulation functions, because that could be prone to error in the future.

**Comment by openingnow** [comment]
```
stack --silent exec brittany
stack --verbosity silent exec brittany
stack --verbosity error exec brittany
```
All of them does not shows version related errors.

**Comment by mnxn** [comment]
Thank you for checking.

Modifying the command that it is called to include `--silent` should fix it then.
I will update the extension when I have the chance.

**Comment by mlantas** [comment]
I added `--verbosity error` as some errors should still be reported.

The extension has been updated to 0.0.9 with the fix. Should be live on the marketplace in a few minutes.
