### ISSUE TITLE
Please update in VS Code Marketplace

### ISSUE THREAD

**Issue by obcode** [MaxGabriel/brittany-vscode-extension#6]
After merging #4 I would love to use it via VS Code Marketplace, i.e. update from within VS Code.

**Comment by MaxGabriel** [comment]
Released as 0.0.2

@mnxn Do you know if there's a way to add you as an authorized uploader of the VSCode extension? I couldn't find such an option

**Comment by mnxn** [comment]
@MaxGabriel I believe if you go to https://marketplace.visualstudio.com/manage/publishers/, and click members, then add, it's possible to add me as a *contributor*. I'll email you my email address so its possible for you to add me.

**Comment by obcode** [comment]
Thanks!
