### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mnxn** [MaxGabriel/brittany-vscode-extension#8]
Currently this repository lacks a license. It would be nice to have one so others would have the freedom to fork this repository or use some of the code from this extension. 

I'd recommend MIT.

Any thoughts?

**Comment by JasonMFry** [comment]
Maybe if you add a License and create a PR for it @MaxGabriel will approve it?

**Comment by mnxn** [comment]
Thank you for the reminder. I'll do that and send an email too. I have push access, so I could commit directly to master if I wanted to (I don't), but I'd much prefer getting input from @MaxGabriel on the License first.
